[package]
name = "common_derive"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "1.0.20"
synstructure = "0.12.6"
proc-macro2 = "1.0.40"

[lib]
 proc-macro = true
