#!/usr/bin/env bash
set -euo pipefail

export LOUVRE_HOME="$(cd "$(dirname "$0")/.." && pwd)"
source "${LOUVRE_HOME}/scripts/aux/core.bash"

main() {
   "${LOUVRE_HOME}/scripts/release" aarch64-linux-android
}

main "$@"