#!/bin/bash
set -euo pipefail

main() {
   local -r config="${1//@/\"}"
   shift || true

   local args="$*"
   args="${args//\//_}"
   args="${args:0:64}"

   local -r tasker_tmp="${TASKER_TMP:-"/sdcard/Tasker/tmp"}"
   local -r timestamp="$(date +"%Y-%m-%dT%H-%M-%S")"
   local log="${tasker_tmp}/louvre_${args}_${timestamp}.txt"
   log="${log//[^0-9a-zA-Z_/]/_}"
   
   mkdir -p "$tasker_tmp" &>/dev/null || true

   for i in "$@"; do
      case "$i" in
         "%"*)
            echo "aborting because of undefined input" > "$log"
            exit 1
            ;;
      esac
   done

   local -r louvre_bin="${LOUVRE_BIN:-"${HOME}/louvre"}"
   "$louvre_bin" --config <(echo "$config") "$@" |& tee "$log"
}

main "$@"