#!/usr/bin/env bash
set -euo pipefail

export LOUVRE_HOME="$(cd "$(dirname "$0")/.." && pwd)"

test_one() {
   set -x
   "${LOUVRE_HOME}/tests/$*"
}

_cargo() {
   cd "$LOUVRE_HOME"
   cargo test
}

main() {
   rm "${LOUVRE_HOME}/tests/run" &>/dev/null || true

   if [[ $# = 0 ]]; then
      _cargo
      IFS=$'\n'
      cd "${LOUVRE_HOME}/tests"
      for t in $(find "." -perm +111 -type f); do
         test_one "$t"
      done
   else
      for i in "$@"; do
         test_one "$i"
      done
   fi
}

main "$@"